teams:
  blue:
    - "blue1"
    - "blue2"
  red:
    - "red1"
    - "red2"

field:
  pxpy: [1, 1, 1]
  pxmy: [2, 2, 2]
  mxpy: [3, 3, 3]
  mxxy: [4, 4, 4]

frames:
  camera: "/external_camera_tf/rgbd_camera_link"
  blue_player: "/blue_player/"

topics:
  subscribe:
    rgb_camera: "/external_camera/rgbd_camera/rgb/image_raw"
    depth_camera: "/external_camera/rgbd_camera/depth/points"
  publish:
    blue_poses: "/blue_team/poses"



